version: 0.2

phases:
  install:
    commands:
      - echo "[Install phase]"
      - npm install

  pre_build:
    commands:
      - echo "[Pre-Build phase]"

  build:
    commands:
      - npx yamllint src/**/*.yml
      - echo "[Build phase]"
      - environment=$(echo $STAGE | tr '[:upper:]' '[:lower:]')
      - aws s3 sync src "s3://iris-survey-file-report-store-${environment}/iris-report-queries/src" --delete
