version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "[Install phase]"
      - npm install

  pre_build:
    commands:
      - echo "[Pre-Build phase]"

  build:
    commands:
      - npx yamllint src/**/*.yml
      - echo "[Build phase]"
      - environment=$(echo $STAGE | tr '[:upper:]' '[:lower:]')
      - aws s3 sync sql/2019 "s3://iris-survey-file-report-store-${environment}/iris-report-queries/src/2019" --delete
      - aws s3 sync sql/2020 "s3://iris-survey-file-report-store-${environment}/iris-report-queries/src/2020" --delete
      - python setup.py bdist_egg
      - cd dist
      - mv iris_report_queries*.egg iris_report_queries.egg
      - cp -r ../lib .
      - cp -r ../queries .
      - aws s3 sync . "s3://doris-code-bucket-${environment}/iris-report-queries/glue-scripts/" --delete
      - cd ..
